<a href="https://colab.research.google.com/github/aakashrana007/Data-Science-Training/blob/main/DAY10_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##NUMPY
>for mathematical calculation-


*   Numbers
*   Strings



NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".


In [ ]:
from sklearn.datasets import load_breast_cancer
cancer_data=load_breast_cancer()
cancer_data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [ ]:
import pandas as pd

>Scikit Learn has already converted the dataset as a array datastructure so we cannot DataFrame it from pandas; for this you need to download the csv file

In [ ]:
cancer_data['data']  #extract only the data value

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
cancer_data['target'] #extract only the target value

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
cancer_data['target_names']   #extract target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
cancer_data['feature_names']  #extract feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
type(cancer_data['data'])  #check the type of data

numpy.ndarray

In [ ]:
cancer_data['data'].shape  #check the shape of data

(569, 30)

In [ ]:
cancer_data['data'][0]  #check the first row of data

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [ ]:
cancer_data['feature_names'][0]  #check the first row of feature_names

'mean radius'

In [ ]:
cancer_data['target'][0]  #check the first row of target

0

In [ ]:
cancer_data['target_names'][0]  #check the first row of target_names

'malignant'

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems.

>**Why use Numpy?**

* Numpy arrays are faster and more compact than Python list.

* An array consumes less memory and is convenient to use.

* Numpy uses much less memory to store data

* code optimization

In [2]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [ ]:
a.ndim  #check the dimension of array

1

In [ ]:
a.shape  #check the shape of array

(5,)

In [ ]:
dir(a)  #check the methods of array

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [ ]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])  #create a 2D array
a

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
a=np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])  #create a 3D array
a

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [ ]:
a.ndim

3

In [ ]:
a = np.array(
    [[[[[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]],
    [[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]]],
    [[[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]],
    [[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9999], [9, 10, 11, 12]]]]],
    [[[[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]],
    [[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]]],
    [[[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]],
    [[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]]]]]
)
a.ndim

6

Thing to keep in mind- 3D array = '[ [ [ '

6D array= '[ [ [ [ [ [ '

In [ ]:
a.shape

(2, 2, 2, 2, 3, 4)

In [ ]:
#find out where *9999* is located
np.where(a==9999)

(array([0]), array([1]), array([1]), array([1]), array([1]), array([3]))

In [ ]:
#manually
a[0][1][1][1][1][3]

9999

In [ ]:
a #for better visualization; count the number of brackets to distinguish

array([[[[[[   1,    2,    3,    4],
           [   5,    6,    8,    9],
           [   9,   10,   11,   12]],

          [[   1,    9,    3,    4],
           [   5,    7,    8,    9],
           [   9,   10,   11,   12]]],


         [[[   1,    2,    3,    4],
           [   5,    6,    8,    9],
           [   9,   10,   11,   12]],

          [[   1,    9,    3,    4],
           [   5,    7,    8,    9],
           [   9,   10,   11,   12]]]],



        [[[[   1,    2,    3,    4],
           [   5,    6,    8,    9],
           [   9,   10,   11,   12]],

          [[   1,    9,    3,    4],
           [   5,    7,    8,    9],
           [   9,   10,   11,   12]]],


         [[[   1,    2,    3,    4],
           [   5,    6,    8,    9],
           [   9,   10,   11,   12]],

          [[   1,    9,    3,    4],
           [   5,    7,    8, 9999],
           [   9,   10,   11,   12]]]]],




       [[[[[   1,    2,    3,    4],
           [   5,    6,    8,    9],
        

**np.ones, np.zeros and np.random**

In [ ]:
np.zeros([10,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros([5,5,5])

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.ones([1,2,3,4])

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [ ]:
np.ones([1,2,3,4])*5

array([[[[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]],

        [[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]]]])

In [ ]:
np.random.randn(10)

array([-0.3202395 , -1.71096204, -0.46729117,  0.92986612, -0.73106323,
        1.03202065, -0.36291251,  0.48240203,  0.38609499,  1.00625596])

In [ ]:
np.random.randn(3,3,2)

array([[[ 0.08583168,  1.26398891],
        [-1.53498977,  0.48420274],
        [-0.93267535, -2.29897413]],

       [[ 0.92134705,  0.45674928],
        [ 0.84882365,  0.78392084],
        [-0.72936651, -0.58509057]],

       [[ 0.18238168, -1.32588211],
        [-0.03697339, -0.42387672],
        [-0.26855214, -0.09575803]]])

**np.arange**

In [ ]:
#to create a array of numbers from 1 to 100
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
#to create an array of even numbers from 0 to 100
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

#Comparison between a normal list and arange (array/ array range)

In [ ]:
import time

iterations = 100000000
before = time.time()
list(range(iterations))
after = time.time()
python_time = after - before
print(f"Python time: {python_time}")

before = time.time()
np.arange(iterations)
after = time.time()
numpy_time = after - before
print(f"Numpy time: {numpy_time}")

print(f"Numpy is {python_time/numpy_time} faster than regular Python.")

Python time: 5.774687051773071
Numpy time: 0.26889777183532715
Numpy is 21.4753994142781 faster than regular Python.


>Sorting

In [ ]:
arr=np.array([9,5,7,3,5,2,6,2,5,1,5,0])
np.sort(arr)  #it is a quick sort

array([0, 1, 2, 2, 3, 5, 5, 5, 5, 6, 7, 9])

>concatenate

In [14]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])
b=np.array([[6,7,8,9,10],[6,7,8,9,10]])
np.concatenate((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10]])

In [15]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

>Reshape

In [ ]:
p=np.arange(10)
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
p.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

Create an array of `64` elements `(64,)` and reshape into
- `(16,4)`
- `(4,4,4)`
- `(8,2,4)`
- `(10,2)`


In [ ]:
af=np.arange(64)
af

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [ ]:
a1=af.reshape(16,4)
print(a1)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]]


In [ ]:
a2=af.reshape(4,4,4)
print(a2)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]


In [ ]:
a3=af.reshape(8,2,4)
print(a3)


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]]

 [[56 57 58 59]
  [60 61 62 63]]]


In [ ]:
a4=af.reshape(10,2)   #cannot reshape caz 10x2!=64
print(a4)

ValueError: cannot reshape array of size 64 into shape (10,2)

>Slicing and indexing

In [16]:
b=np.array([1,2,3])
b[0]

1

In [18]:
b[0:2]

array([1, 2])

In [19]:
b[1:]

array([2, 3])

In [22]:
b[-2:]

array([2, 3])

In [25]:
data=np.array([[3,6,5],[7,8,4]])
data

array([[3, 6, 5],
       [7, 8, 4]])

In [26]:
data[1][1]

8

In [27]:
data[1,1]

8

In [38]:
data[1,2]

4

In [39]:
data[-1,-1]

4

>Conditions:

In [32]:
a=np.array([[1,2,3,4,5],[5,3,7,8,2],[9,10,11,12,4]])
a

array([[ 1,  2,  3,  4,  5],
       [ 5,  3,  7,  8,  2],
       [ 9, 10, 11, 12,  4]])

In [33]:
a[a<5]

array([1, 2, 3, 4, 3, 2, 4])

In [34]:
a[a>=6]

array([ 7,  8,  9, 10, 11, 12])

In [40]:
five_up=(a>=5)
a[five_up]

array([ 5,  5,  7,  8,  9, 10, 11, 12])

* Create a array with numbers from 1 to 50.
* Filter only the even numbers from the array.

In [41]:
n=np.arange(1,51)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [42]:
only_even=(n%2==0)
n[only_even]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])