<a href="https://colab.research.google.com/github/aakashrana007/Data-Science-Training/blob/main/DAY11_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
a=np.array([5,6,7,8])
a=[5,6,7,8]

>EXERCISE:

*Double each elements i.e  [10,12,14,16]

> 1. Using normal python approach:

**Lamda Function-** for a line of code/function.

In [ ]:
li=[5,6,7,8]
list(map(lambda x:x*2,li))

[10, 12, 14, 16]

> 2. Using Numpy

In [ ]:
a=np.array(li)
a*2

array([10, 12, 14, 16])

**Trigonometry**

In [ ]:
s=np.array([5,6,7,1.5708])
np.sin(s)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  1.        ])

In [ ]:
np.cos(s)

array([ 2.83662185e-01,  9.60170287e-01,  7.53902254e-01, -3.67320510e-06])

In [ ]:
np.tan(s)

array([-3.38051501e+00, -2.91006191e-01,  8.71447983e-01, -2.72241808e+05])

**Linear Algebra**

Create two np arrays with random numbers with dimension 2,3 and 3,2.

In [ ]:
a=np.random.randn(2,3)
b=np.random.randn(3,2)
a


array([[ 0.44784939, -1.33297376, -0.96615936],
       [-0.7451883 ,  0.61880302, -3.01503061]])

In [ ]:
b

array([[-0.52704447, -0.00587485],
       [ 0.62967898, -0.88486506],
       [-0.92309655,  0.12600556]])

In [ ]:
np.dot(a,b) #matrix multiplication

array([[-0.18352373,  1.05512941],
       [ 3.56555901, -0.92308994]])

In [ ]:
np.matmul(a,b)  #matrix multiplication

array([[-0.18352373,  1.05512941],
       [ 3.56555901, -0.92308994]])

> Create a random matrix of shape (1000,3) and create another with a shape (3,1000) . Check the shape of the resultant matrix after multiplication.

In [ ]:
mat=np.random.randn(1000,3)
mab=np.random.randn(3,1000)
max=np.dot(mat,mab)
max.shape

(1000, 1000)

> **Transpose**

* Create a numpy array od range 10
* Reshape it to (5,2)


# Numpy Exercises
Multiply the following two NumPy arrays element-wise: [1, 2, 3] and [4, 5, 6], and print the result.

Calculate the mean of the following NumPy array: [3, 7, 10, 15, 19], and print the result.

Reshape the following NumPy array into a 2x3 matrix: [1, 2, 3, 4, 5, 6].

Find the maximum value in the following NumPy array: [9, 2, 7, 5, 3], and print it.


**More exercises**

Create a 2D NumPy array with shape (5, 5) containing random integers between 1 and 100. Replace all values greater than 50 with 0 and print the modified array.

Create a 1D NumPy array with 20 elements ranging from 0 to 100. Reshape the array into a 4x5 matrix and print it.

Create a 3x3 matrix with random values between 0 and 1. Replace all values less than 0.5 with 0 and print the modified matrix.

Create a 1D NumPy array with 100 elements ranging from 1 to 100. Reshape the array into a 10x10 matrix and calculate the sum of each row. Print the sum.

Create a 2D NumPy array with shape (4, 4) containing random integers between 1 and 10. Find the indices of the maximum value in each row and print the indices.

Create a 1D NumPy array with 50 random elements randomly. Calculate the mean and standard deviation of the array and print the results.

Create a 2D NumPy array with shape (3, 3) and fill it with values ranging from 0 to 8. Shuffle the rows randomly and print the shuffled array.

Create a 1D NumPy array with 100 elements ranging from 1 to 10. Replace all odd values with -1 and print the modified array.

Create a 3x3 matrix with random values between 0 and 1. Normalize the matrix by dividing each row by the sum of its elements and print the normalized matrix.

Create a 2D NumPy array with shape (5, 5) and fill it with random values between 0 and 1. Sort the elements in each column in descending order and print the sorted array.

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a*b

array([ 4, 10, 18])

In [ ]:
b=np.array([3, 7, 10, 15, 19])
np.mean(b)

10.8

In [ ]:
c=np.array([1, 2, 3, 4, 5, 6] )
c.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d=np.array( [9, 2, 7, 5, 3])
np.max(d)

9

> Create a 2D NumPy array with shape (5, 5) containing random integers between 1 and 100. Replace all values greater than 50 with 0 and print the modified array.

In [ ]:
e=np.random.randint(1,100,size=(5,5))
e[e>50]=0
e

array([[ 0,  0, 18,  0,  0],
       [ 0,  0,  0, 15, 30],
       [18,  0,  0, 20,  0],
       [ 1, 12,  0, 21,  1],
       [21, 20, 50, 44, 30]])

> Create a 1D NumPy array with 20 elements ranging from 0 to 100. Reshape the array into a 4x5 matrix and print it.

In [ ]:
f=np.random.randint(1,100,size=(20))
f

array([ 3, 75, 14, 78, 52, 26, 21, 60, 91, 86,  2, 65, 89, 91, 99, 35, 82,
       13, 36, 20])

In [ ]:
f.reshape(4,5)

array([[ 3, 75, 14, 78, 52],
       [26, 21, 60, 91, 86],
       [ 2, 65, 89, 91, 99],
       [35, 82, 13, 36, 20]])

> Create a 3x3 matrix with random values between 0 and 1. Replace all values less than 0.5 with 0 and print the modified matrix.

In [ ]:
g=np.random.uniform(0,1,size=(3,3))   #generate random float numbers in given range
g

array([[0.07976796, 0.5675467 , 0.5563824 ],
       [0.68350278, 0.37222583, 0.02258564],
       [0.55436604, 0.47558194, 0.71452329]])

In [ ]:
g[g<0.5]=0
g

array([[0.        , 0.5675467 , 0.5563824 ],
       [0.68350278, 0.        , 0.        ],
       [0.55436604, 0.        , 0.71452329]])

> Create a 1D NumPy array with 100 elements ranging from 1 to 100. Reshape the array into a 10x10 matrix and calculate the sum of each row. Print the sum.

In [ ]:
h=np.arange(1,101)  #1D array with 100 elements
h
h

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

>NOTE

np.arange us typically used for 1D arrays however you can reshape it

In [ ]:
h_reshaped=h.reshape(10,10)
h_reshaped

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
np.sum(h)  #sum of all elements

5050

>NOTE

* *Axis 0 :* This is the vertical direction (down the rows). When you operate along axis 0, you're performing the operation **across rows, for each column.**
* *Axis 1 :* This is the horizontal direction (across the columns). When you operate along axis 1, you're performing the operation **across columns, for each row.**

In [ ]:
np.sum(h_reshaped,axis=0)  #sum of each column

array([460, 470, 480, 490, 500, 510, 520, 530, 540, 550])

In [ ]:
np.sum(h_reshaped,axis=1)  #sum of each row

array([ 55, 155, 255, 355, 455, 555, 655, 755, 855, 955])

> Create a 2D NumPy array with shape (4, 4) containing random integers between 1 and 10. Find the indices of the maximum value in each row and print the indices.

In [3]:
i=np.random.randint(1,10,size=(4,4))
i

array([[7, 4, 8, 3],
       [2, 4, 1, 7],
       [9, 9, 7, 9],
       [8, 4, 1, 6]])

In [12]:
max=i.max(axis=1)  #max of each row
max

array([8, 7, 9, 8])

In [15]:
np.argmax(i,axis=1)  #index of max of each row

array([2, 3, 0, 0])

> Create a 1D NumPy array with 50 random elements randomly. Calculate the mean and standard deviation of the array and print the results

In [28]:
j=np.random.randn(50)
j

array([-2.21587228e-03, -1.51864699e+00,  9.26876413e-01,  2.31048795e-01,
        3.38448586e-01,  8.07867378e-01,  2.43651587e-01,  7.99236510e-01,
        1.67675472e+00,  1.31405252e-01,  7.47601812e-01,  3.56178333e-01,
       -7.89792632e-01, -2.48922102e+00,  7.26359145e-01, -1.70556349e-02,
        1.22415153e+00, -5.78342937e-01, -5.81665780e-01,  6.47424308e-01,
       -2.25154439e-01, -1.50761165e+00,  7.73988497e-01,  1.02268724e+00,
        1.94946663e+00, -9.95627555e-01,  4.73267884e-01,  2.57944548e-01,
        9.63663932e-01, -1.27139562e+00,  1.98647613e-01, -3.37804850e-01,
        4.91800981e-01, -1.53602301e+00, -2.70893895e-01,  1.96209378e+00,
       -7.04826931e-01, -1.67619487e+00,  1.25741213e+00,  1.79064837e+00,
        5.89578566e-01, -1.68787315e+00,  1.35743398e-01,  9.21429775e-01,
        1.22954630e+00,  9.52118286e-01,  8.61437808e-02,  4.32942000e-01,
        2.60745898e-01,  1.72973466e+00])

In [29]:
j.mean()  #mean

0.20292523589282646

In [30]:
j.std()  #standard deviation

1.021596970498929

> Create a 2D NumPy array with shape (3, 3) and fill it with values ranging from 0 to 8. Shuffle the rows randomly and print the shuffled array.

In [33]:
k=np.random.randint(0,8, size=(3,3))
k

array([[3, 1, 2],
       [5, 7, 7],
       [2, 7, 7]])

In [36]:
np.random.shuffle(k)  #shuffling rows
k

array([[5, 7, 7],
       [3, 1, 2],
       [2, 7, 7]])

> Create a 1D NumPy array with 100 elements ranging from 1 to 10. Replace all odd values with -1 and print the modified array.

In [37]:
l=np.random.randint(1,10, size=(100))
l

array([1, 2, 8, 2, 3, 7, 5, 6, 5, 4, 7, 7, 9, 3, 4, 4, 5, 7, 4, 8, 8, 1,
       9, 2, 5, 2, 6, 7, 3, 3, 6, 1, 7, 3, 6, 6, 9, 4, 4, 3, 1, 8, 6, 9,
       3, 9, 3, 1, 6, 7, 8, 3, 6, 9, 4, 8, 5, 2, 5, 6, 7, 7, 3, 7, 8, 9,
       7, 2, 6, 5, 6, 3, 3, 1, 4, 1, 7, 2, 1, 4, 5, 1, 2, 4, 6, 6, 5, 7,
       2, 1, 6, 1, 1, 9, 3, 5, 1, 8, 6, 6])

In [44]:
l[l%2!=0]=-1
l

array([-1,  2,  8,  2, -1, -1, -1,  6, -1,  4, -1, -1, -1, -1,  4,  4, -1,
       -1,  4,  8,  8, -1, -1,  2, -1,  2,  6, -1, -1, -1,  6, -1, -1, -1,
        6,  6, -1,  4,  4, -1, -1,  8,  6, -1, -1, -1, -1, -1,  6, -1,  8,
       -1,  6, -1,  4,  8, -1,  2, -1,  6, -1, -1, -1, -1,  8, -1, -1,  2,
        6, -1,  6, -1, -1, -1,  4, -1, -1,  2, -1,  4, -1, -1,  2,  4,  6,
        6, -1, -1,  2, -1,  6, -1, -1, -1, -1, -1, -1,  8,  6,  6])

> Create a 3x3 matrix with random values between 0 and 1. Normalize the matrix by dividing each row by the sum of its elements and print the normalized matrix.

In [61]:
m=np.random.uniform(0,1,size=(3,3))
m=np.round(m,2)  #rounding to 2 decimal places
m

array([[0.51, 0.15, 0.46],
       [0.2 , 0.42, 0.52],
       [0.76, 0.71, 0.12]])

In [65]:
for i in m:
  i=i/i.sum(axis=0)
  i=np.round(i,2)
  print(i)

[0.46 0.13 0.41]
[0.18 0.37 0.46]
[0.48 0.45 0.08]


> Create a 2D NumPy array with shape (5, 5) and fill it with random values between 0 and 1. Sort the elements in each column in descending order and print the sorted array.

In [67]:
n=np.random.uniform(0,1,size=(5,5))
n

array([[0.06059998, 0.78623906, 0.84172858, 0.7618754 , 0.78035978],
       [0.40500385, 0.0216395 , 0.01537724, 0.75347981, 0.55481971],
       [0.21994326, 0.04226089, 0.34557671, 0.5831539 , 0.97971026],
       [0.2002349 , 0.15420308, 0.91951681, 0.83809879, 0.05603785],
       [0.41836409, 0.8563111 , 0.31232362, 0.56673186, 0.572855  ]])

In [73]:
np.sort(n,axis=0)  #sorting each column in ascending order


array([[0.06059998, 0.0216395 , 0.01537724, 0.56673186, 0.05603785],
       [0.2002349 , 0.04226089, 0.31232362, 0.5831539 , 0.55481971],
       [0.21994326, 0.15420308, 0.34557671, 0.75347981, 0.572855  ],
       [0.40500385, 0.78623906, 0.84172858, 0.7618754 , 0.78035978],
       [0.41836409, 0.8563111 , 0.91951681, 0.83809879, 0.97971026]])

In [75]:
# Sort the array along axis=0 (columns) in descending order
np.sort(n, axis=0)[::-1]

array([[0.41836409, 0.8563111 , 0.91951681, 0.83809879, 0.97971026],
       [0.40500385, 0.78623906, 0.84172858, 0.7618754 , 0.78035978],
       [0.21994326, 0.15420308, 0.34557671, 0.75347981, 0.572855  ],
       [0.2002349 , 0.04226089, 0.31232362, 0.5831539 , 0.55481971],
       [0.06059998, 0.0216395 , 0.01537724, 0.56673186, 0.05603785]])

In [76]:
# Sort the array along axis=1 (rows) in descending order
np.sort(n, axis=1)[:, ::-1]

array([[0.84172858, 0.78623906, 0.78035978, 0.7618754 , 0.06059998],
       [0.75347981, 0.55481971, 0.40500385, 0.0216395 , 0.01537724],
       [0.97971026, 0.5831539 , 0.34557671, 0.21994326, 0.04226089],
       [0.91951681, 0.83809879, 0.2002349 , 0.15420308, 0.05603785],
       [0.8563111 , 0.572855  , 0.56673186, 0.41836409, 0.31232362]])

**Explanation:**

np.sort(n, axis=0) sorts the array n along the columns (axis 0) in ascending order.

[::-1] reverses the order of the sorted array to make it descending.

np.sort(n, axis=1) sorts the array n along the rows (axis 1) in ascending order.

[:, ::-1] reverses the order of each row in the sorted array to make it descending.